config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'minpaku#index'

  get 'survey' => 'survey#index'
  post 'survey/answer' => 'survey#answer'
  get 'get_aggregate_values/:id' => 'minpaku#get_aggregate_values'
end

app/models/admin_user.rb
# frozen_string_literal: true

class AdminUser < ApplicationRecord
  has_secure_password
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/minpaku.rb
# frozen_string_literal: true

class Minpaku < ApplicationRecord
  has_many :surveys
  has_many :survey_comments, through: :surveys
  has_many :survey_values, through: :surveys

  self.inheritance_column = :_type_disabled

  def set_aggregate_values
    self.aggregate_values = self.get_aggregate_values
  end

  def get_aggregate_values
    result = ActiveRecord::Base.connection.select_all("SELECT 
        AVG(minpaku_values.value) AS average,
        survey_lists.survey_name
      FROM
        survey_lists
        INNER JOIN
          (SELECT 
            survey_values.value,
            survey_values.survey_list_id,
            surveys.minpaku_id
          FROM
            survey_values
          INNER JOIN surveys ON survey_values.survey_id = surveys.id
          WHERE minpaku_id = #{self.id}) AS minpaku_values 
        ON survey_lists.id = minpaku_values.survey_list_id
        GROUP BY survey_lists.survey_name;
      ")
      return result
  end

  def get_comments
  end
end

app/models/survey.rb
# frozen_string_literal: true

class Survey < ApplicationRecord
  belongs_to :minpaku
  has_one :survey_comment
  has_many :survey_values
end

app/models/survey_comment.rb
# frozen_string_literal: true

class SurveyComment < ApplicationRecord
  belongs_to :survey
end

app/models/survey_list.rb
# frozen_string_literal: true

class SurveyList < ApplicationRecord
  has_many :survey_values
end

app/models/survey_value.rb
# frozen_string_literal: true

class SurveyValue < ApplicationRecord
  belongs_to :survey
  belongs_to :survey_list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/minpaku_controller.rb
# frozen_string_literal: true

class MinpakuController < ApplicationController
  after_action :allow_iframe, only: [:index, :get_aggregate_values, :get_comments]

  def index
    @minpaku_list = Minpaku.all
    @survey_list = SurveyList.all
    
    gon.minpaku_all = @minpaku_list
  end

  def get_aggregate_values
    render :json => Minpaku.find(request[:id]).get_aggregate_values
  end

  def get_comments
    render :json => Minpaku.find(request[:id]).get_comments
  end

  private
  def allow_iframe
    url="http://codeforota.tokyo"
    response.headers['X-Frame-Options'] = "ALLOW-FROM #{url}"
    response.headers['Content-Security-Policy'] = "frame-ancestors #{url}"
  end
end

app/controllers/survey_controller.rb
class SurveyController < ApplicationController
    def index
        @minpaku = Minpaku.find(params[:minpaku_id])
        @survey_list = SurveyList.all
    end

    def answer
        minpaku_id = params[:minpaku_id]
        survey_list = SurveyList.all

        survey = Survey.create!(minpaku_id: minpaku_id)

        survey_list.each do |survey_content|
            id = survey_content.id
            SurveyValue.create!(survey_id: survey.id, value: params["survey_#{id}"], survey_list_id: id)
        end

        SurveyComment.create(survey_id: survey.id, comment: params[:survey_comment])

        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/minpaku_helper.rb
module MinpakuHelper
end

app/helpers/survey_helper.rb
module SurveyHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>MinpakuServer</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= include_gon %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>
  <div id="top-bar">
    <div id="logo">
      <img src="/assets/main/Logo00.png" width="200" height="200" />
    </div>

    <div id="main-title-wrapper">
      <div id="main-title-text">
        <%= link_to "大田区 民泊 MAP", root_path %>
      </div>
    </div>

    <div id="about-page-details">
      <div id="about-wrapper">
        <div class="about_list_wrapper">
          <div id="about" class="about_list">
            <a href="/assets/main/report/Code for OTA 第一回レポート.pdf">レポートについて</a>
          </div>
        </div>
        <div class="about_list_wrapper">
          <div id="privacy-policy-wrapper" class="about_list">
            <a href="/assets/main/privacypolicyCFO.pdf">個人情報保護</a>
          </div>
        </div>
      </div>
    </div>
  </div>

  <%= yield %>
</body>

</html>

app/views/minpaku/index.html.erb
<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD7B0ZTz7BZZLQ4E7cPD77Ns2mih7u3y5U&callback=initMap"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.min.js"
  integrity="sha512-d9xgZrVZpmmQlfonhQUvTR7lMPtO7NkZMkA0ABN3PHCbKA5nqylQ/yWlFAyY6hYgdF1Qh6nYiuADWwKB4C2WSw=="
  crossorigin="anonymous"></script>

<div id="main">
  <div id="map"></div>
  <div id="adverts">
    <div class="ad">
      ad1
    </div>
    <div class="ad">
      ad2
    </div>
  </div>
</div>

<script>
  var isModalDisplay = false;

  function initMap() {
    var latlng = new google.maps.LatLng(
      gon.minpaku_all[0].latitude,
      gon.minpaku_all[0].longitude
    ); //中心の緯度, 経度
    var map = new google.maps.Map(document.getElementById("map"), {
      zoom: 14, //ズームの調整
      center: latlng //上で設定した中心
    });

    var markers = [];
    var info_windows = [];

    for (var i = 0; i < gon.minpaku_all.length; i++) {
      markers[i] = new google.maps.Marker({
        position: new google.maps.LatLng(
          gon.minpaku_all[i].latitude,
          gon.minpaku_all[i].longitude
        ),
        map: map,
        icon: "/assets/main/home_icon_main_1.png"
      });

      var minpaku_name = gon.minpaku_all[i].name ? gon.minpaku_all[i].name : "無名の民泊";

      var html =
        `<div class="modal" id="modal_` + gon.minpaku_all[i].id + `">
                    <div class="close_button" id="close_button_` + gon.minpaku_all[i].id + `">
                      <div class="close_icon_modal">
                        <img src="/assets/main/modal/x.png" width="20" height="20">
                      </div>
                      <div class="close_text" onclick=closeInfoWindow(` + gon.minpaku_all[i].id + `)>
                        ウィンドウを閉じる
                      </div>
                    </div>
                    <div class="minpaku_name_area minpaku_basic_info">
                      <div class="home_icon_modal">
                        <img src="/assets/main/modal/home_icon_modal_1.png" widtth="40" height="40">
                      </div>
                      <div class="minpaku_name">
                      ` +
        minpaku_name +
        `
                      </div>
                    </div>

                    <div class="minpaku_location_area minpaku_basic_info">
                      <div class="address_icon_modal">
                        <img src="/assets/main/modal/address_modal.png" widtth="30" height="30">
                      </div>
                      <div class = "address_area">
                        <div class ="postal_code">
                        〒 ` +
        gon.minpaku_all[i].postal_code +
        `
                        </div>
                        <div class="address_full">
                        ` +
        gon.minpaku_all[i].prefecture +
        gon.minpaku_all[i].city +
        gon.minpaku_all[i].address_details +
        `
                        </div>
                      </div>
                    </div>

                    <div class="move_to_survey minpaku_basic_info">
                      <a href="/survey?minpaku_id=` +
        gon.minpaku_all[i].id +
        `">アンケートに回答する</a>
                    </div>

                    <div class="aggregate_values">
                    <canvas id="chart_id_` +
        gon.minpaku_all[i].id +
        `" width="400" height="400"></canvas>

                    </div>

                    <div id="comment_id_"` +
        gon.minpaku_all[i].id +
        `>
                    </div>

                  </div>`;

      info_windows[i] = new google.maps.InfoWindow({
        content: html
      });

      google.maps.event.addListener(
        markers[i],
        "click",
        (function (i) {
          return function () {
            info_windows[i].open(map, markers[i]);
            add_aggregate_values_dom(gon.minpaku_all[i].id);
            //add_close_event_click_other_area(info_windows[i], gon.minpaku_all[i].id);
            //isModalDisplay = true;
            //add_comment_dom(gon.minpaku_all[i], id);
          };
        })(i)
      );

      /*
      モーダルの外をクリックした時にモーダルを閉じる
            function add_close_event_click_other_area(info_window, i) {
              document.addEventListener("click", function (e) {
                if (isModalDisplay && !e.target.closest("#modal_" + i)) {
                  info_window.close();
                  isModalDisplay = false;
                }
              })
            }
      */

      function add_aggregate_values_dom(id) {
        var request = new XMLHttpRequest();
        request.open("GET", "/get_aggregate_values/" + id, true);
        request.onload = function () {
          build_radar_chart(this.response, id);
        };
        request.send();
      }

      function add_comment_dom(id) {
        var request = new XMLHttpRequest();
        request.open("GET", "/get_comments/" + id, true);
        //要作成
        request.onload = function () {
          var comments_area = document.getElementById("comment_id_" + id);
          comments_area.innerHTML = comments_html_builder(this.response, id);
        };
        request.send();
      }

      function build_radar_chart(response, id) {
        var labels = [];
        var values = [];

        var aggregate_values = JSON.parse(response);

        aggregate_values.forEach(aggregate_value => {
          labels.push(aggregate_value.survey_name);
          values.push(aggregate_value.average * 10);
        });

        var target = document.getElementById("chart_id_" + id);
        var radarChart = new Chart(target, {
          type: "radar",
          data: {
            labels: labels,
            datasets: [{
              label: "近隣住民からの評価",
              data: values,
              backgroundColor: "rgba(96, 183, 220, 0.5)",
              borderColor: "rgba(96, 183, 220, 0.5)"
            }]
          },
          options: {
            scale: {
              ticks: {
                suggestedMin: 0,
                suggestedMax: 10,
                fontSize: 12
              },
              pointLabels: {
                fontSize: 16
              }
            },
            legend: {
              display: true,
              labels: {
                fontSize: 16
              }
            }
          }
        });
      }

      function comments_html_builder(response, id) {}
    }
  }
</script>

app/views/survey/index.html.erb
<div id="questionaire">

  <div id="minpaku_name">
    <%= @minpaku.name %>についてのアンケート調査
  </div>

  <div id="subtitle">
    アンケート項目
  </div>

  <%= form_tag(survey_answer_path, method: :post) do %>
  <%= hidden_field_tag :minpaku_id, @minpaku.id %>
  <div>
    <table>
      <thead>
        <tr class="table_header">
          <th>No.</th>
          <th>質問</th>
          <th>Good</th>
          <th>Bad</th>
        </tr>
      </thead>
      <tbody>
        <% @survey_list.each do |survey| %>
        <tr class="table_content">
          <th><%= survey.id %></th>
          <th><%= survey.survey_name %></th>
          <th><%= radio_button_tag "survey_#{survey.id}", 1 %></th>
          <th><%= radio_button_tag "survey_#{survey.id}", 0 %></th>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div id="free-comment">
    <div id="free-comment-label">
      自由記述欄
    </div>
    <div id="free-comment-textarea">
      <%= text_area_tag "survey_comment" %>
    </div>
  </div>

  <div id="submit-button">
    <%= submit_tag "送信" %>
  </div>
  <% end %>
</div>